name: GET UP

on:
  schedule:
    - cron: "0 01 * * *" 
    
  workflow_dispatch:
    inputs:
      message:
        description: "weather message"
        required: false

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GEMINI_IMAGEN_API_KEY: ${{ secrets.GEMINI_IMAGEN_API_KEY }}
  GEMINI_IMAGEN_API_BASE: ${{ secrets.GEMINI_IMAGEN_API_BASE }}
  GEMINI_IMAGEN_MODEL: ${{ secrets.GEMINI_IMAGEN_MODEL }}
  UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPO: ${{ github.repository }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
  TIAN_API_KEY: ${{ secrets.TIAN_API_KEY }}

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: GET UP
        run: |
          python moning_main.py --weather ": ${{ github.event.inputs.message }}"

      - name: Push New Pic
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add OUT_DIR/* || echo "No new images to add"
            git commit -m "generated today pic" || echo "No changes to commit"
            git pull --rebase origin main
            git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
